

// types for students



module.exports = {
    VIEW_STUDENT_INFO: 'VIEW_STUDENT_INFO',
    VIEW_STUDENT_NOTE: 'VIEW_STUDENT_NOTE',
    VIEW_STUDENT_ROOM: 'VIEW_STUDENT_ROOM',
    VIEW_STUDENT_PER_ROOM:'VIEW_STUDENT_PER_ROOM',

    //teachers:
    VIEW_TEACHER_INFO: 'VIEW_TEACHER_INFO',
    VIEW_TEACHER_COURSE: 'VIEW_TEACHER_COURSE',
    VIEW_TEACHER_ROOM: 'VIEW_TEACHER_ROOM'
}



// types for salones

// types for profesores